// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwxtqpswfpermekxregw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3eHRxcHN3ZnBlcm1la3hyZWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjkyNjUsImV4cCI6MjA2ODMwNTI2NX0.P_pmhY1KsaS0FDRtrsupKaRq5_S8kktL6THaVABBZFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});